// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv91NFkPK1kiOoMq6773UOV9t8HKyRnvg',
    appId: '1:811278434716:web:83c5d44b60ee7a51bfc859',
    messagingSenderId: '811278434716',
    projectId: 'audiomood-abb34',
    authDomain: 'audiomood-abb34.firebaseapp.com',
    storageBucket: 'audiomood-abb34.firebasestorage.app',
    measurementId: 'G-S5CQ2LLD6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ7dJ-qoDV-2YVm0GZ384w2BUsZU0BaR8',
    appId: '1:811278434716:android:abf0dfb1a86e7cdbbfc859',
    messagingSenderId: '811278434716',
    projectId: 'audiomood-abb34',
    storageBucket: 'audiomood-abb34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8ITGBZULl_4REntLh5GkrfwLefIVcHyE',
    appId: '1:811278434716:ios:2277fb5ed4e5924abfc859',
    messagingSenderId: '811278434716',
    projectId: 'audiomood-abb34',
    storageBucket: 'audiomood-abb34.firebasestorage.app',
    iosBundleId: 'com.example.audiomood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8ITGBZULl_4REntLh5GkrfwLefIVcHyE',
    appId: '1:811278434716:ios:2277fb5ed4e5924abfc859',
    messagingSenderId: '811278434716',
    projectId: 'audiomood-abb34',
    storageBucket: 'audiomood-abb34.firebasestorage.app',
    iosBundleId: 'com.example.audiomood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv91NFkPK1kiOoMq6773UOV9t8HKyRnvg',
    appId: '1:811278434716:web:dc86c2e5200f5728bfc859',
    messagingSenderId: '811278434716',
    projectId: 'audiomood-abb34',
    authDomain: 'audiomood-abb34.firebaseapp.com',
    storageBucket: 'audiomood-abb34.firebasestorage.app',
    measurementId: 'G-PB0NPST2Q6',
  );
}
